In [ ]:
import numpy as np
import pandas as pd

In [ ]:
data = pd.read_csv("/content/Social_Network_Ads (1).csv")
data.head()

User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510    Male   19            19000          0
1  15810944    Male   35            20000          0
2  15668575  Female   26            43000          0
3  15603246  Female   27            57000          0
4  15804002    Male   19            76000          0

In [ ]:
data.isnull().sum()

User ID            0
Gender             0
Age                0
EstimatedSalary    0
Purchased          0
dtype: int64

In [ ]:
x = data.iloc[:,[2,3]].values
y = data.iloc[:,4]

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=30)


In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test =sc.transform(x_test)

In [ ]:
x_train.shape

(320, 2)

In [ ]:
y_train.shape

(320,)

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
KNN = KNeighborsClassifier(n_neighbors= 5 , metric= "minkowski" )
KNN.fit(x_train,y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                     weights='uniform')

In [ ]:
x_train.shape

(320, 2)

In [ ]:
y_train.shape

(320,)

In [ ]:
y_pred = KNN.predict(x_test)
print("predicted value:",y_pred)

predicted value: [0 1 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 1 0 0 1 1 1 0 0 1 1 0 0 1 0
 1 1 0 0 1 0 1 0 0 0 0 0 1 0 0 0 0 0 1 1 1 0 0 1 0 0 1 0 0 0 1 0 0 0 0 1 1
 0 0 1 0 1 1]


In [ ]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test,y_pred)
print(cm)


[[49  0]
 [ 4 27]]


In [ ]:
from sklearn.metrics import accuracy_score
accuracy_knn = accuracy_score(y_test,y_pred)
print("accuracy:",accuracy_knn)

accuracy: 0.95


KNN using Salary data set

SVM

In [ ]:
import numpy as np
import pandas as pd
data=pd.read_csv("/content/Social_Network_Ads (1).csv")
data.head()
x=data.iloc[:,[2,3]].values
y = data.iloc[:,4].values
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=23)
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)
from sklearn.svm import SVC
svc = SVC()#default kernel = "rbf"
svc.fit(x_train,y_train)
svc_pred = svc.predict(x_test)
print(svc_pred)
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test,svc_pred)
print(cm)
#accuracy
from sklearn.metrics import accuracy_score
accuracy_SVM = accuracy_score(y_test,svc_pred)
print("accuracy:",accuracy_SVM)

[0 1 0 0 1 0 1 1 1 1 0 1 0 0 0 1 1 0 1 0 0 0 0 0 0 0 0 0 1 1 0 0 0 1 1 0 0
 0 1 0 1 0 1 0 1 1 1 0 1 1 0 0 0 0 0 1 1 0 1 1 0 0 1 1 0 0 1 0 0 0 1 0 0 0
 1 0 0 1 1 0]
[[45  5]
 [ 2 28]]
accuracy: 0.9125


by using kernals in svm

In [ ]:
#kernel = linear
from sklearn.svm import SVC
svc = SVC(kernel= 'linear')
svc.fit(x_train,y_train)
#predict the test results
svc_pred = svc.predict(x_test)
print(svc_pred)
#confusion matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test,svc_pred)
print(cm)
#accuracy
from sklearn.metrics import accuracy_score
acc_score = accuracy_score(y_test,svc_pred)
acc_score

[0 1 0 0 1 0 1 1 1 0 0 1 0 0 0 0 1 0 1 0 0 0 0 0 0 0 0 0 0 1 0 0 0 1 0 1 0
 0 0 0 0 0 0 0 1 0 1 0 1 1 0 0 0 0 0 1 0 0 0 1 0 0 0 1 0 0 1 0 0 0 1 0 0 0
 1 0 0 1 1 0]
[[47  3]
 [10 20]]


0.8375

In [ ]:
#kernel = sigmoid
from sklearn.svm import SVC
svc = SVC(kernel= 'sigmoid')
svc.fit(x_train,y_train)
#predict the test results
svc_pred = svc.predict(x_test)
print(svc_pred)
#confusion matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test,svc_pred)
print(cm)
#accuracy
from sklearn.metrics import accuracy_score
acc_score = accuracy_score(y_test,svc_pred)
acc_score


[0 0 0 1 0 1 0 0 0 1 0 1 1 0 1 0 0 1 0 0 0 0 0 0 0 1 0 0 1 0 0 1 0 1 0 0 0
 0 1 0 0 0 0 0 0 1 0 1 0 0 1 1 0 0 0 0 1 0 1 0 1 0 1 0 0 1 0 1 0 1 0 0 1 0
 0 0 0 0 0 0]
[[35 15]
 [21  9]]


0.55

In [ ]:
#kernel = "poly"
from sklearn.svm import SVC
svc = SVC(kernel= 'poly')
svc.fit(x_train,y_train)
#predict the test results
svc_pred = svc.predict(x_test)
print(svc_pred)
#confusion matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test,svc_pred)
print(cm)
#accuracy
from sklearn.metrics import accuracy_score
acc_score = accuracy_score(y_test,svc_pred)
acc_score

[0 1 0 0 1 0 0 1 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 1 0 0
 0 0 0 1 0 1 0 1 0 1 0 1 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 1 0 0 0 0 0 0 0
 1 0 0 1 0 0]
[[46  4]
 [18 12]]


0.725

#decision Tree Classifier

In [ ]:
import numpy as np
import pandas as pd
data = pd.read_csv("/content/Social_Network_Ads (1).csv")
data.head()
x = data.iloc[:,[2,3]].values
y =data.iloc[:,4].values
#test train split
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.2,random_state = 43)
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)
#model
from sklearn.tree import DecisionTreeClassifier
DT = DecisionTreeClassifier()
DT.fit(x_train,y_train)
#predict
DT_pred = DT.predict(x_test)
print(DT_pred)
#cm
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test,DT_pred)
print(cm)
#accuracy
acc_score = accuracy_score(y_test,DT_pred)
acc_score


[0 1 1 0 1 0 1 0 1 0 0 0 0 0 1 1 0 1 1 0 1 1 1 0 1 0 0 1 0 1 0 1 0 1 0 0 1
 1 0 1 0 1 0 1 0 0 0 1 0 0 0 1 1 1 1 1 0 0 1 0 0 0 1 0 0 0 0 0 0 0 1 0 1 0
 0 0 0 1 1 0]
[[43  7]
 [ 3 27]]


0.875

Random forest classifier

In [ ]:
import pandas as pd
import numpy as np
data = pd.read_csv("/content/Social_Network_Ads (1).csv")
data.head()
x = data.iloc[:,[2,3]].values
y = data.iloc[:,4].values
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test =  train_test_split(x,y,test_size=0.2,random_state=34)
from sklearn.preprocessing import StandardScaler
sc= StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)
from sklearn.ensemble import RandomForestClassifier
RF = RandomForestClassifier(n_estimators = 10,criterion = 'entropy')
RF.fit(x_train,y_train)
#predict
RF_pred = RF.predict(x_test)
print(RF_pred)
#cm
from sklearn.metrics import confusion_matrix,accuracy_score
cm = confusion_matrix(y_test,RF_pred)
print(cm)
#accuracy
Acc_score = accuracy_score(y_test,RF_pred)
print(Acc_score)

[0 0 1 1 1 0 0 1 1 0 1 1 0 1 0 0 0 0 0 0 1 0 1 1 0 0 0 1 0 0 1 1 1 0 0 0 0
 1 1 0 1 1 0 0 1 0 0 0 0 1 0 0 1 1 0 0 0 1 1 0 0 1 0 0 0 1 1 0 0 1 0 0 0 0
 0 1 0 0 0 0]
[[43  6]
 [ 7 24]]
0.8375
